export const PRIVACY_POLICY = `
# Privacy Policy

**Effective Date: May 11, 2026**

Welcome to Red Flag Scanner. We take your privacy (and your trauma) seriously.

## 1. Data Collection
We do **not** store your chat screenshots or text descriptions permanently on our servers. The data you provide is sent to our AI engine for real-time analysis and is discarded shortly after the report is generated.

## 2. No Selling of Data
We do not sell, rent, or trade your personal information. We're here to roast, not to profit from your data leaks.

## 3. AI Generated Content
The analysis provided is generated by artificial intelligence. It is intended for entertainment purposes only and should not be treated as factual evidence or professional advice.

## 4. User Responsibility
You are responsible for the content you upload. Please ensure you have the necessary permissions to share any third-party information or likenesses. Do not upload sensitive PII (Personally Identifiable Information).

## 5. Security
We use industry-standard encryption to protect your data during transmission. However, no internet transmission is 100% secure.
`;

export const TERMS_OF_SERVICE = `
# Terms of Service

## 1. Acceptance of Terms
By using Red Flag Scanner, you agree to these terms. If you don't agree, please stop being toxic and leave the app.

## 2. Entertainment Only
This app is for **umor and entertainment purposes only**. The "Toxicity Scores" and "Katne Ka Chance" are fictional metrics generated by AI.

## 3. No Professional Advice
We are not therapists, lawyers, or relationship counselors. Do not make life-altering decisions based on a roast.

## 4. User Conduct
You agree not to use the app to harass, threaten, or harm others. We reserve the right to block access to anyone using the service for malicious purposes.

## 5. Limitation of Liability
We are not responsible for any emotional damage, breakups, or system hangs resulting from the use of this app. Use at your own risk.
`;

export const DISCLAIMER = `
# Disclaimer

**IMPORTANT: READ BEFORE YOU GET ROASTED**

### 1. Accuracy
Red Flag Scanner uses AI to analyze relationship dynamics. AI can hallucinate, exaggerate, and be plain wrong. Results are not factually accurate.

### 2. Not a Diagnostic Tool
This is not a psychological assessment. High toxicity scores do not constitute a clinical diagnosis of any personality disorder.

### 3. Vibe Check Only
This app investigates "vibes," not actual legal cases. We are not responsible for how you interpret the "forensic autopsy."

### 4. Share Safely
When sharing results on social media, you do so at your own risk. Be mindful of the privacy of others mentioned in your stories.
`;
